POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jhon",
    "lastName": "Doe",
    "email": "shubhaseesh09@gmail.com",
    "phone": "+919876543287",
    "password": "123456789"
}